# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fb8c62af7c18fff4de60b5b7b0877d02175c5c80c291129e9dbd8a315bc5e017fd52b6c01a02e291d3e729b2b6b3f794eb73abeeeb536ae5b15c5207dcc19c9

test:
  secret_key_base: 9a5a2ea31cc71c7254ba515cc057bc33cb79fecfd6aeefaf4c54fef08d5a1c7de87d76094982e6e7e7ea571c5b9ff362b679ec3028451185764df92c82e5d5f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
